# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mohammad Haghighipoor
subtitle: Software developer | Critical Thinking | Problem Solving.
avatar_url: https://yt3.googleusercontent.com/ytc/AIdro_n_YQF-h1SXlCvBODbAaQuLJvA6mmjqO8zQ94XFfkT-2Lk=s176-c-k-c0x00ffffff-no-rj

email: mohammad.haghighi.poor@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The day doesn't run me; I run the day,
  I make sure every single day has a clear and well-communicated structure.
  It also means changes are welcome.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ohamhpr.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

youtube_username: mohammadhaghighipoor3044
linkedin_username:  ohamhpr
github_username:  ohamhpr
twitter_username: ohamhpr
stack_overflow_username:  ohamhpr
instagram_username:  ohamhpr

under_construction_message: Thank you for your interest!<br/>
  I'm making some improvements and will have everything ready soon.

# Build settings
# theme: minima
plugins:
  - jekyll-feed

collections:
  ideas:
    output: true
  projects:
    output: true
  experiences:
    output: true

defaults:
  - scope:
      path: ""
      type: "ideas"
    values:
      layout: single
  - scope:
      path: ""
      type: "projects"
    values:
      layout: single
  - scope:
      path: ""
      type: "experiences"
    values:
      layout: single
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
